Repository alefragnani/vscode-pascal-formatter, pull requests merged in 2023-02, with the labels that each got.

#52 Add Quadroid JEDI Code Format engine
  package.json
  src/extension.ts
  src/formatter.ts
Labels: enhancement, good first issue, external tools

#56 Features/support translation localization
  l10n/bundle.l10n.json
  l10n/bundle.l10n.pt-br.json
  package.json
  package.nls.json
  package.nls.pt-br.json
  src/extension.ts
  src/formatter.ts
Labels: enhancement, vscode api adoption

#58 Update badges in README (Closes #57)
  README.md
Labels: Internal
